### ISSUE TITLE
i have taked erorr: "/bin/bash: ./darknet: No such file or directory"

### ISSUE THREAD

**Issue by IZIEIRIOI** [roboflow/notebooks#28]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbnJERWU5czNTUjJfMFZoTmM4ZHNFcnJsZzdqQXxBQ3Jtc0trSHRNdlRMVm1hLVZuMkpnMV9MR192TXVVYnRuOW9lVjZKa1pNeWFlSi1TSzFQNmJ0ZXR3WnU5SXZheUQ1dXNrQ3dEZjh3c2FBTGhTU3FlRWpRZDhPTURPUnZDRXFHVWtVamtmYWgyX2dRVE1ONUFhQQ&q=https%3A%2F%2Fcolab.research.google.com%2Fdrive%2F1mzL6WyY9BRx4xX476eQdhKDnd_eixBlG%23scrollTo%3DGNVU7eu9CQj3&v=N-GS8cmDPog

### Bug

![Screenshot (226)](https://user-images.githubusercontent.com/121150420/208831820-b7683576-7a3f-460d-9586-cfa84522fc9e.png)
/bin/bash: ./darknet: No such file or directory

### Environment

- Google Colab

### Minimal Reproducible Example

!./darknet detector train data/obj.data cfg/custom-yolov4-detector.cfg yolov4.conv.137 -dont_show -map 
#If you get CUDA out of memory adjust subdivisions above!
#adjust max batches down for shorter training above

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @IZIEIRIOI 👋🏻! Thanks for your interest in [Roboflow Notebooks](https://github.com/roboflow/notebooks). I'll try to take a look at this issue today. I'll keep you posted.

**Comment by LokeshSaipureddi** [comment]
Hi @SkalskiP  even I am facing the same issue from yesterday

**Comment by LokeshSaipureddi** [comment]
But the issue is in different notebook. The notebook name is  YOLOv4-tiny-Darknet-Roboflow.ipynb

**Comment by IZIEIRIOI** [comment]
Hi @SkalskiP, please sir fix it thist bug, before I could train the yolo4-dakrnet model, but now it can't, because I'm undergo my thesis with this model

**Comment by IZIEIRIOI** [comment]
Hi @LokeshSaipureddi, then you can fix it sir in notebook name yolov4 tiny darknet ?

**Comment by SkalskiP** [comment]
Hi @LokeshSaipureddi and @IZIEIRIOI! Sorry, it takes so long.

**Comment by SkalskiP** [comment]
@Jacobsolawetz, I could use your help here! 🥺 

It looks like we have problems with installing the darknet on Google Colab on K80 GPU. I think Google must have updated Colab environment. But I never really worked with Darknet. Could you take a look?

**Comment by IZIEIRIOI** [comment]
@Jacobsolawetz, please sir can you fix it this bug ?

**Comment by LokeshSaipureddi** [comment]
@SkalskiP  Its not issue with K80 GPU. Colab has changed its gpu to Tesla T4 from Tesla K80. So, Installation was not working in Tesla T4 GPU

**Comment by LokeshSaipureddi** [comment]
![image](https://user-images.githubusercontent.com/66957108/209072281-7842c538-411c-4540-9a9c-1ed05dde72c7.png)
![image](https://user-images.githubusercontent.com/66957108/209072725-d522cde9-1287-4277-9e84-a51b693438d3.png)
In this Image darknet file was installed. That file was not installed which was causing the error. That file was missing.

**Comment by IZIEIRIOI** [comment]
![Screenshot (233)](https://user-images.githubusercontent.com/121150420/209088846-3c03657e-f843-4082-ac01-11178d0b638c.png)
@LokeshSaipureddi yep your right, i try to install then this happen, error --"

**Comment by LokeshSaipureddi** [comment]
![image](https://user-images.githubusercontent.com/66957108/209107875-f5731b87-f923-4189-a3f6-2a933112e668.png)
@IZIEIRIOI 
Line 5 is commented in this cell try uncommenting it. Then you will see error but you can see darknet file will be created in darknet folder. This will work !!!.

**Comment by LokeshSaipureddi** [comment]
@SkalskiP I want you to update this notebook accordingly. Thank you !!!!

**Comment by LokeshSaipureddi** [comment]
Yes training is working after that change.

**Comment by SkalskiP** [comment]
I’m off today. I’ll test the fix tomorrow and if it will work then I release the update.

**Comment by SkalskiP** [comment]
@LokeshSaipureddi I just tested that solution, and it doesn't work for me. Could you send me the version of the notebook that worked for you?

**Comment by Strizerz** [comment]
> 

It doesn't work for me either after doing that change but I also did receive an error in the console when I was  installing Darknet for YOLOv4 on Colab - "Makefile:162: recipe for target 'obj/convolutional_layer.o' failed" I have no clue what that means but I am letting you know that I get that when I run the step

**Comment by SkalskiP** [comment]
@Strizerz, that fix does not work for me either. That bug is a bit problematic as YOLOv4 does not mention that project anymore. We will try to fight it regardless.

**Comment by fatihcihant** [comment]
The same problem continues.

**Comment by seyedamirhh** [comment]
it doesn't work, 

1. in installing Darknet: error: compilation terminated due to -Wfatal-errors.
make: *** [Makefile:162: obj/convolutional_layer.o] Error 1
2. in Train Custom YOLOv4 Detector: /bin/bash: ./darknet: No such file or directory

**Comment by wolverineV2** [comment]
Did you solve the Problem? Because in the Last week it doesn`t work and for some reason yesterday it worked !
And today with the same Code there is again the bin/bash Error

**Comment by SkalskiP** [comment]
@wolverineV2, unfortunately, that issue is still active. We did not manage to solve it. s for YOLOv3 - anything that uses Darknet will suffer from that issue. The biggest problem is that no one is supporting those models anymore. :/

**Comment by hirosichen** [comment]
Is the issue solved? I am facing the same issue.

**Comment by SkalskiP** [comment]
Unfortunately not yet.

**Comment by hirosichen** [comment]
I suggest Roboflow can refet to below and modify your repo. This will build reputation of your product. Otherwise, many people will feel frustrated after following your tutorial video about building custom yolo v4 model.

https://colab.research.google.com/drive/1zqRb08ljHvIIMR4fgAXeNy1kUtjDU85B?usp=sharing
